<?php

/**
 * ForumMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ForumMessageTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumMessage');
    }
}