<?php

/**
 * ForumThreadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumThreadTable extends ForumMessageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return ForumThreadTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumThread');
    }
}