prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:

  .actions:
    # Authentication
    login_module:           sfGuardAuth
    login_action:           signin

    # Authorization
    secure_module:          sfGuardAuth
    secure_action:          secure

  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            377decb9a94058f58f4f1b893e777df3566cf7fd

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    i18n:                   true
    standard_helpers:       [ Partial, Cache, Date, Text, Number, I18N ]
    enabled_modules:        [default, sfGuardAuth, sfGuardRegister, sfGuardForgotPassword ]
